"""add_requested_role_to_users

Revision ID: 0d1cbc6f1ae4
Revises: bf79dff49e59
Create Date: 2026-09-03 17:35:44.523815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1cbc6f1ae4'
down_revision: Union[str, Sequence[str], None] = 'bf79dff49e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # create_type=False: the 'user_role' Postgres enum type already exists
    # (created by an earlier migration for the `role` column). Without this,
    # SQLAlchemy tries to CREATE TYPE user_role again and errors with
    # "type already exists".
    op.add_column(
        'users',
        sa.Column(
            'requested_role',
            sa.Enum('SUPERUSER', 'ADMIN', 'RECRUITER', 'USER', name='user_role', create_type=False),
            nullable=True,
        ),
    )
    # NOTE: the autogenerated drop_index/create_index of 'one_superuser_only'
    # was removed here. That index is the DB-level guarantee that only one
    # row can have role='SUPERUSER' — unrelated to this column addition.
    # Alembic's autogenerate false-positives on Postgres partial indexes
    # (the postgresql_where clause isn't always introspected identically to
    # how it was declared), so it proposed dropping/recreating an index that
    # never actually changed. Applying that would have briefly removed the
    # single-superuser constraint for no reason.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'requested_role')