"""add applications table

Revision ID: 19146a6586f9
Revises: bc2092792553
Create Date: 2026-09-08 13:54:05.502323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19146a6586f9'
down_revision: Union[str, Sequence[str], None] = 'bc2092792553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'HIRED', name='application_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_application_user_job')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('one_superuser_only'), 'users', ['role'], unique=True, postgresql_where="(role = 'SUPERUSER'::user_role)")
    op.drop_table('applications')
    # ### end Alembic commands ###
