"""add jd blob storage and skills extraction retry columns

Revision ID: 6d292f70d295
Revises: 6d7734b43aa4
Create Date: 2026-09-22 14:59:15.342198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d292f70d295'
down_revision: Union[str, Sequence[str], None] = '6d7734b43aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('jobs', sa.Column('blob_path', sa.String(length=1000), nullable=True))
    op.add_column('jobs', sa.Column('original_filename', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('content_type', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('jobs', sa.Column('skills_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('skills_section_heading', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column(
        'skills_extraction_status',
        sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='job_extraction_status'),
        nullable=False,
        server_default='PENDING',
    ))
    op.add_column('jobs', sa.Column('skills_extraction_error', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('skills_extracted_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column(
        'skills_extraction_retry_count', sa.Integer(), nullable=False, server_default='0',
    ))
    op.add_column('resumes', sa.Column(
        'skills_extraction_retry_count', sa.Integer(), nullable=False, server_default='0',
    ))
    op.alter_column('jobs', 'skills_extraction_status', server_default=None)
    op.alter_column('jobs', 'skills_extraction_retry_count', server_default=None)
    op.alter_column('resumes', 'skills_extraction_retry_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'skills_extraction_retry_count')
    op.drop_column('jobs', 'skills_extraction_retry_count')
    op.drop_column('jobs', 'skills_extracted_at')
    op.drop_column('jobs', 'skills_extraction_error')
    op.drop_column('jobs', 'skills_extraction_status')
    op.drop_column('jobs', 'skills_section_heading')
    op.drop_column('jobs', 'skills_result')
    op.drop_column('jobs', 'size_bytes')
    op.drop_column('jobs', 'content_type')
    op.drop_column('jobs', 'original_filename')
    op.drop_column('jobs', 'blob_path')
    # ### end Alembic commands ###
