"""add avatar and application resume

Revision ID: 7081755dc02d
Revises: 2f06ddd5aa36
Create Date: 2026-09-09 12:45:22.689596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7081755dc02d'
down_revision: Union[str, Sequence[str], None] = '2f06ddd5aa36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'applications', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('avatar_blob_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_blob_path')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'resume_id')
    # ### end Alembic commands ###
