"""phase2 job and user extended fields

Revision ID: 925e0c6fdb88
Revises: 78edcfe13254
Create Date: 2026-09-03 11:33:37.913352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '925e0c6fdb88'
down_revision: Union[str, Sequence[str], None] = '78edcfe13254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # explicit enum type creation — op.add_column does not create the
    # Postgres enum type automatically (unlike op.create_table), so these
    # must exist before the columns below reference them
    postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='employment_type').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ENTRY', 'MID', 'SENIOR', 'LEAD', 'EXECUTIVE', name='seniority_level').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ONSITE', 'REMOTE', 'HYBRID', name='remote_type').create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='employment_type'), nullable=False, server_default='FULL_TIME'))
    op.add_column('jobs', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('seniority', sa.Enum('ENTRY', 'MID', 'SENIOR', 'LEAD', 'EXECUTIVE', name='seniority_level'), nullable=True))
    op.add_column('jobs', sa.Column('remote_type', sa.Enum('ONSITE', 'REMOTE', 'HYBRID', name='remote_type'), nullable=True))
    op.add_column('jobs', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('min_experience_years', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_experience_years', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('education_requirement', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('closes_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('desired_role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'desired_role')
    op.drop_column('users', 'location')
    op.drop_column('users', 'experience_years')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'title')
    op.drop_column('users', 'company')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_column('jobs', 'closes_at')
    op.drop_column('jobs', 'published_at')
    op.drop_column('jobs', 'education_requirement')
    op.drop_column('jobs', 'max_experience_years')
    op.drop_column('jobs', 'min_experience_years')
    op.drop_column('jobs', 'required_skills')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    op.drop_column('jobs', 'remote_type')
    op.drop_column('jobs', 'seniority')
    op.drop_column('jobs', 'department')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###

    # drop the enum types last, after every column referencing them is gone
    postgresql.ENUM(name='remote_type').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='seniority_level').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='employment_type').drop(op.get_bind(), checkfirst=True)