"""empty message

Revision ID: bc2092792553
Revises: 0d1cbc6f1ae4
Create Date: 2026-09-08 10:45:25.257582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2092792553'
down_revision: Union[str, Sequence[str], None] = '0d1cbc6f1ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recruiter_rejected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recruiter_rejected_at')
    # ### end Alembic commands ###
