"""add resume experience

Revision ID: c7d8e9f0a1b2
Revises: 380033278259
Create Date: 2026-09-30 07:24:29.767684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7d8e9f0a1b2'
down_revision: Union[str, Sequence[str], None] = '380033278259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('experience_months', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('experience_entries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'experience_entries')
    op.drop_column('resumes', 'experience_months')
    # ### end Alembic commands ###
