"""
All skill alias data, plus the code that builds the final lookup table.

Shape: canonical skill name -> list of alternate spellings / phrasings / versions
that should be treated as that same skill.

skill_aliases.py builds SKILL_ALIASES at import time by merging CURATED_ALIASES
with EXTRA_GROUPS inverted (alias -> canonical). Hand-written entries in
CURATED_ALIASES always win.

Rules for this file:
  * Pure data + alias builder function. Import nothing from the app, so it can never cause a circular import.
  * Keep everything lowercase; matching lowercases skills before lookup.
  * To add an alias, append it to the right list. To add a skill, add a new key
    under the matching section header.
"""

CURATED_ALIASES = {
    # =========================
    # Languages
    # =========================
    "py": "python",
    "python3": "python",
    "python 3": "python",
    "python3.x": "python",
    "js": "javascript",
    "javascript es6": "javascript",
    "javascript es2015": "javascript",
    "ecmascript": "javascript",
    "es6": "javascript",
    "es2015": "javascript",
    "es2020": "javascript",
    "es2021": "javascript",
    "es2022": "javascript",
    "es2023": "javascript",
    "ts": "typescript",
    "typescriptlang": "typescript",
    "golang": "go",
    "go lang": "go",
    "go-lang": "go",
    "c sharp": "c#",
    "c-sharp": "c#",
    "csharp": "c#",
    "c plus plus": "c++",
    "cpp": "c++",
    "c/c++": "c++",
    "objective c": "objective-c",
    "objc": "objective-c",
    "shell scripting": "shell",
    "shell script": "shell",
    "bash scripting": "bash",
    "bash shell": "bash",
    "zsh shell": "zsh",
    "powershell scripting": "powershell",
    "ps": "powershell",

    # =========================
    # Frontend
    # =========================
    "reactjs": "react",
    "react.js": "react",
    "react js": "react",
    "reactjs.js": "react",
    "vuejs": "vue",
    "vue.js": "vue",
    "vue js": "vue",
    "angularjs": "angular",
    "angular.js": "angular",
    "angular js": "angular",
    "nextjs": "next.js",
    "next js": "next.js",
    "next": "next.js",
    "nuxtjs": "nuxt",
    "nuxt.js": "nuxt",
    "sveltejs": "svelte",
    "svelte.js": "svelte",
    "jquery.js": "jquery",
    "j query": "jquery",
    "html5": "html",
    "html 5": "html",
    "css3": "css",
    "css 3": "css",
    "scss": "sass",
    "sass/scss": "sass",
    "lesscss": "less",
    "tailwindcss": "tailwind css",
    "tailwind": "tailwind css",
    "material ui": "mui",
    "material-ui": "mui",
    "materialui": "mui",
    "chakraui": "chakra ui",
    "chakra-ui": "chakra ui",
    "react-native": "react native",

    # =========================
    # Node / JavaScript
    # =========================
    "node": "node.js",
    "nodejs": "node.js",
    "node js": "node.js",
    "node.js runtime": "node.js",
    "expressjs": "express",
    "express.js": "express",
    "express js": "express",
    "nestjs": "nest.js",
    "nest js": "nest.js",
    "npmjs": "npm",
    "npm.js": "npm",
    "pnpmjs": "pnpm",
    "yarnpkg": "yarn",
    "webpackjs": "webpack",
    "vitejs": "vite",
    "rollupjs": "rollup",

    # =========================
    # Python
    # =========================
    "fast api": "fastapi",
    "fast-api": "fastapi",
    "fast_api": "fastapi",
    "django-rest-framework": "django rest framework",
    "drf": "django rest framework",
    "flask api": "flask",
    "sql alchemy": "sqlalchemy",
    "sql-alchemy": "sqlalchemy",
    "pydantic v2": "pydantic",
    "pydantic2": "pydantic",
    "pytest framework": "pytest",
    "py test": "pytest",
    "pandas python": "pandas",
    "numpy python": "numpy",
    "scikit learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "scikit_learn": "scikit-learn",

    # =========================
    # SQL
    # =========================
    "postgres": "postgresql",
    "postgresql db": "postgresql",
    "postgres db": "postgresql",
    "postgres database": "postgresql",
    "postgresql database": "postgresql",
    "psql": "postgresql",
    "pgsql": "postgresql",
    "mysql db": "mysql",
    "mysql database": "mysql",
    "mariadb db": "mariadb",
    "mssql": "sql server",
    "ms sql": "sql server",
    "ms-sql": "sql server",
    "microsoft sql server": "sql server",
    "sqlserver": "sql server",
    "sql server database": "sql server",
    "oracle db": "oracle",
    "oracle database": "oracle",
    "sqlite3": "sqlite",
    "sqlite db": "sqlite",
    "sqlite database": "sqlite",

    # =========================
    # NoSQL
    # =========================
    "mongo": "mongodb",
    "mongo db": "mongodb",
    "mongodb db": "mongodb",
    "mongodb database": "mongodb",
    "redis db": "redis",
    "redis cache": "redis",
    "elastic search": "elasticsearch",
    "elastic-search": "elasticsearch",
    "elastic": "elasticsearch",
    "cassandra db": "cassandra",
    "dynamodb db": "dynamodb",
    "dynamo db": "dynamodb",
    "amazon dynamodb": "dynamodb",
    "cosmos db": "azure cosmos db",
    "cosmosdb": "azure cosmos db",

    # =========================
    # SQL / DB concepts
    # =========================
    "structured query language": "sql",
    "sql queries": "sql",
    "sql query": "sql",
    "pl/sql": "plsql",
    "pl sql": "plsql",
    "t-sql": "tsql",
    "t sql": "tsql",
    "db design": "database design",
    "database schema design": "database design",
    "dbms": "database management",
    "rdbms": "relational database",
    "relational db": "relational database",
    "object relational mapping": "orm",
    "object-relational mapping": "orm",

    # =========================
    # AWS
    # =========================
    "amazon web services": "aws",
    "amazon aws": "aws",
    "aws cloud": "aws",
    "amazon ec2": "aws ec2",
    "ec2": "aws ec2",
    "amazon s3": "aws s3",
    "s3": "aws s3",
    "s3 bucket": "aws s3",
    "amazon rds": "aws rds",
    "rds": "aws rds",
    "lambda": "aws lambda",
    "amazon eks": "aws eks",
    "eks": "aws eks",
    "amazon ecs": "aws ecs",
    "ecs": "aws ecs",
    "cloudwatch": "aws cloudwatch",
    "aws cloud watch": "aws cloudwatch",

    # =========================
    # Azure
    # =========================
    "microsoft azure": "azure",
    "azure cloud": "azure",
    "ms azure": "azure",
    "azure vm": "azure virtual machines",
    "azure virtual machine": "azure virtual machines",
    "azure blob": "azure blob storage",
    "blob storage": "azure blob storage",
    "azure adls": "azure data lake storage",
    "adls": "azure data lake storage",
    "adls gen2": "azure data lake storage",
    "azure data lake": "azure data lake storage",
    "azure data lake storage gen2": "azure data lake storage",
    "azure function": "azure functions",
    "azure sql": "azure sql database",
    "azure sql db": "azure sql database",

    # =========================
    # GCP
    # =========================
    "google cloud": "gcp",
    "google cloud platform": "gcp",
    "google compute engine": "gcp compute engine",
    "gce": "gcp compute engine",
    "google cloud storage": "gcp cloud storage",
    "gcs": "gcp cloud storage",
    "google kubernetes engine": "gke",
    "google cloud functions": "gcp cloud functions",

    # =========================
    # Containers / DevOps
    # =========================
    "docker container": "docker",
    "docker containers": "docker",
    "dockerized": "docker",
    "dockerisation": "docker",
    "dockerization": "docker",
    "k8s": "kubernetes",
    "kube": "kubernetes",
    "kubernetes cluster": "kubernetes",
    "kubernetes orchestration": "kubernetes",
    "containerisation": "containerization",
    "docker-compose": "docker compose",
    "helm charts": "helm",
    "helm chart": "helm",
    "tf": "terraform",
    "ansible automation": "ansible",
    "ansible playbooks": "ansible",

    # =========================
    # CI/CD
    # =========================
    "ci cd": "ci/cd",
    "ci/cd pipeline": "ci/cd",
    "cicd": "ci/cd",
    "ci-cd": "ci/cd",
    "continuous integration": "ci/cd",
    "continuous deployment": "ci/cd",
    "continuous delivery": "ci/cd",
    "github-action": "github actions",
    "gitlab ci": "gitlab ci/cd",
    "gitlab-ci": "gitlab ci/cd",
    "gitlab cicd": "gitlab ci/cd",
    "jenkins pipeline": "jenkins",
    "jenkins ci": "jenkins",
    "ado": "azure devops",

    # =========================
    # Git
    # =========================
    "git version control": "git",
    "git scm": "git",
    "version control": "git",
    "git hub": "github",
    "git lab": "gitlab",
    "svn": "subversion",
    "apache subversion": "subversion",

    # =========================
    # APIs / Backend
    # =========================
    "rest": "rest api",
    "restful": "rest api",
    "restful api": "rest api",
    "rest apis": "rest api",
    "restful apis": "rest api",
    "http api": "rest api",
    "http apis": "rest api",
    "web api": "rest api",
    "web apis": "rest api",
    "graphql api": "graphql",
    "graph ql": "graphql",
    "grpc api": "grpc",
    "g-rpc": "grpc",
    "soap api": "soap",
    "soap web services": "soap",
    "microservice": "microservices",
    "micro-services": "microservices",
    "micro service": "microservices",
    "oauth2": "oauth 2.0",
    "oauth 2": "oauth 2.0",
    "oauth2.0": "oauth 2.0",
    "jwt auth": "jwt",
    "jwt authentication": "jwt",
    "json web token": "jwt",
    "json web tokens": "jwt",

    # =========================
    # Messaging
    # =========================
    "apache kafka": "kafka",
    "kafka streaming": "kafka",
    "rabbitmq broker": "rabbitmq",
    "rabbit mq": "rabbitmq",
    "apache pulsar": "pulsar",
    "message queues": "message queue",
    "message queueing": "message queue",
    "messaging queues": "message queue",

    # =========================
    # AI / ML / NLP
    # =========================
    "artificial intelligence": "ai",
    "machine intelligence": "ai",
    "ml": "machine learning",
    "dl": "deep learning",
    "natural language processing": "nlp",
    "natural-language processing": "nlp",
    "text processing": "nlp",
    "large language model": "llm",
    "large language models": "llm",
    "llms": "llm",
    "gen ai": "generative ai",
    "genai": "generative ai",
    "huggingface": "hugging face",
    "hugging-face": "hugging face",
    "hf": "hugging face",
    "transformers library": "hugging face transformers",
    "huggingface transformers": "hugging face transformers",
    "hf transformers": "hugging face transformers",
    "sentence transformers": "sentence-transformers",
    "sentence_transformers": "sentence-transformers",
    "vector db": "vector database",
    "vector databases": "vector database",
    "vector store": "vector database",
    "pinecone db": "pinecone",
    "chroma db": "chromadb",
    "chromadb database": "chromadb",

    # =========================
    # Data / Analytics
    # =========================
    "data analysis": "data analytics",
    "extract transform load": "etl",
    "extract-transform-load": "etl",
    "apache spark": "spark",
    "spark sql": "spark",
    "py spark": "pyspark",
    "apache airflow": "airflow",
    "airflow orchestration": "airflow",
    "powerbi": "power bi",
    "tableau desktop": "tableau",

    # =========================
    # Testing
    # =========================
    "unit tests": "unit testing",
    "integration tests": "integration testing",
    "automated testing": "test automation",
    "jestjs": "jest",
    "jest.js": "jest",
    "mocha.js": "mocha",
    "mochajs": "mocha",
    "cypress.io": "cypress",
    "playwright testing": "playwright",
    "selenium webdriver": "selenium",
    "selenium web driver": "selenium",

    # =========================
    # Observability / SRE
    # =========================
    "prometheus monitoring": "prometheus",
    "grafana dashboards": "grafana",
    "elk": "elk stack",
    "elastic stack": "elk stack",
    "application performance monitoring": "apm",
    "opentelemetry": "open telemetry",
    "otel": "open telemetry",

    # =========================
    # Security
    # =========================
    "application security": "appsec",
    "app security": "appsec",
    "cyber security": "cybersecurity",
    "cyber-security": "cybersecurity",
    "infosec": "information security",
    "iam": "identity and access management",
    "role based access control": "rbac",
    "role-based access control": "rbac",
    "single sign on": "sso",
    "single-sign-on": "sso",
    "multi factor authentication": "mfa",
    "multi-factor authentication": "mfa",
    "2fa": "mfa",
    "two factor authentication": "mfa",

    # =========================
    # Architecture
    # =========================
    "system architecture": "system design",
    "object oriented programming": "oop",
    "object-oriented programming": "oop",
    "oops": "oop",
    "data structures and algorithms": "dsa",
    "data structures & algorithms": "dsa",
    "ds and algo": "dsa",
    "event driven architecture": "event-driven architecture",
    "domain driven design": "domain-driven design",
    "ddd": "domain-driven design",

    # =========================
    # Java
    # =========================
    "java 8": "java",
    "java 11": "java",
    "java 17": "java",
    "java 21": "java",
    "jdk": "java",
    "jre": "java",
    "springboot": "spring boot",
    "spring-boot": "spring boot",
    "spring framework": "spring",
    "hibernate orm": "hibernate",
    "hibernate framework": "hibernate",
    "maven build": "maven",
    "apache maven": "maven",
    "gradle build": "gradle",

    # =========================
    # .NET
    # =========================
    "dotnet": ".net",
    "dot net": ".net",
    "microsoft .net": ".net",
    "aspnet core": "asp.net core",
    "asp net core": "asp.net core",
    "ef core": "entity framework core",

    # =========================
    # Mobile
    # =========================
    "android development": "android",
    "android sdk": "android",
    "ios development": "ios",
    "ios sdk": "ios",
    "flutter development": "flutter",
    "dart language": "dart",

    # =========================
    # Infrastructure
    # =========================
    "linux os": "linux",
    "gnu/linux": "linux",
    "unix system": "unix",
    "nginx web server": "nginx",
    "nginx server": "nginx",
    "apache http server": "apache",
    "load balancer": "load balancing",

    # =========================
    # Infrastructure as Code
    # =========================
    "iac": "infrastructure as code",
    "infrastructure-as-code": "infrastructure as code",
    "terraform iac": "terraform",
    "terraform cloud": "terraform",

    # =========================
    # Project / Agile
    # =========================
    "agile methodology": "agile",
    "agile development": "agile",
    "scrum methodology": "scrum",
    "scrum framework": "scrum",
    "kanban methodology": "kanban",
    "jira software": "jira",
    "atlassian jira": "jira",
    "confluence atlassian": "confluence",

    # =========================
    # Common abbreviations
    # =========================
    "apis": "api",
    "db": "database",
    "dbs": "database",
    "dev ops": "devops",
    "dev-ops": "devops",
    "devops engineering": "devops",
    "sre": "site reliability engineering",
    "qa": "quality assurance",
    "quality engineering": "quality assurance",
    "ui ux": "ui/ux",
    "ui/ux design": "ui/ux",
    "ux ui": "ui/ux",
    "frontend": "frontend development",
    "front end": "frontend development",
    "front-end": "frontend development",
    "backend": "backend development",
    "back end": "backend development",
    "back-end": "backend development",
    "fullstack": "full-stack development",
    "full stack": "full-stack development",
    "full-stack": "full-stack development",
}

EXTRA_GROUPS = {
    # ===== Languages =====
    "python": ["python2", "python 2", "python programming", "python development", "python scripting", "cpython",
               "python 3.x", "python 3.8", "python 3.9", "python 3.10", "python 3.11", "python 3.12"],
    "javascript": ["java script", "vanilla js", "vanilla javascript", "javascript programming", "javascript development",
                   "es 6", "es6+", "es7", "es8", "modern javascript", "client side javascript", "client-side javascript"],
    "typescript": ["type script", "typescript programming", "typescript development"],
    "java": ["java programming", "core java", "java se", "java 7", "java 9", "java 10", "java 12", "java 13", "java 14",
             "java 15", "java 16", "java 18", "java 19", "java 20", "java development", "openjdk", "oracle jdk",
             "java 8+", "j2se", "java core"],
    "java ee": ["j2ee", "jakarta ee", "java enterprise edition", "javaee", "java ee 8"],
    "c": ["c language", "c programming", "ansi c"],
    "c++": ["c++ programming", "c++11", "c++14", "c++17", "c++20", "modern c++", "cplusplus", "c++ development", "cxx"],
    "c#": ["c# programming", "c# development", "c#.net"],
    "go": ["go programming", "go language", "golang development", "go development"],
    "rust": ["rust lang", "rust programming", "rustlang"],
    "ruby on rails": ["rails", "ror", "rubyonrails", "ruby-on-rails", "ruby on rails framework"],
    "php": ["php programming", "php7", "php 7", "php8", "php 8", "php development"],
    "laravel": ["laravel framework", "laravel php"],
    "swift": ["swift programming", "swift language"],
    "swiftui": ["swift ui"],
    "kotlin": ["kotlin programming", "kotlin lang"],
    "scala": ["scala programming", "scala lang"],
    "perl": ["perl scripting", "perl programming"],
    "r": ["r programming", "r language", "r lang"],
    "vba": ["visual basic for applications", "excel vba", "vba macros", "excel macros"],
    "vb.net": ["vbnet", "visual basic .net", "visual basic.net", "vb .net"],
    "visual basic": ["vb6", "visual basic 6"],
    "shell": ["unix shell", "unix shell scripting", "shell scripts", "shell programming"],
    "bash": ["bash script", "bash scripts", "bash programming", "bash commands"],
    "cron": ["cron jobs", "cronjobs", "crontab", "cron job", "cron scheduling"],

    # ===== Frontend =====
    "react": ["react 16", "react 17", "react 18", "react 19", "react hooks", "react library", "react-js", "reactjs library"],
    "redux": ["reduxjs", "redux.js", "react redux", "react-redux"],
    "redux toolkit": ["rtk", "redux-toolkit", "reduxjs toolkit", "reduxjs/toolkit"],
    "react router": ["react-router", "react-router-dom", "react router dom", "reactrouter"],
    "tanstack query": ["react query", "react-query", "tanstack react query", "tanstack-query"],
    "next.js": ["next.js 13", "next.js 14", "next 13", "next 14", "nextjs 13", "nextjs 14", "next.js framework", "nextjs framework"],
    "vue": ["vue 2", "vue 3", "vue2", "vue3", "vue.js 2", "vue.js 3", "vuejs 3", "vue framework"],
    "nuxt": ["nuxt 3", "nuxt3", "nuxt js"],
    "angular": ["angular 2+", "angular 2", "angular 4", "angular 6", "angular 8", "angular 9", "angular 10", "angular 11",
                "angular 12", "angular 13", "angular 14", "angular 15", "angular 16", "angular 17", "angular 18",
                "angular framework", "angular cli"],
    "rxjs": ["rx.js", "rx js", "reactive extensions"],
    "sveltekit": ["svelte kit", "svelte-kit"],
    "solidjs": ["solid.js", "solid js"],
    "astro": ["astro.js", "astrojs"],
    "remix": ["remix.run", "remixjs", "remix run"],
    "gatsby": ["gatsbyjs", "gatsby.js"],
    "jquery": ["j-query", "jquery library", "jquery plugins"],
    "bootstrap": ["bootstrap 3", "bootstrap 4", "bootstrap 5", "bootstrap3", "bootstrap4", "bootstrap5", "twitter bootstrap",
                  "bootstrap css", "bootstrap framework", "react bootstrap", "react-bootstrap"],
    "tailwind css": ["tailwind-css", "tailwind v3", "tailwind v4", "tailwindcss 3", "tailwind css 3", "tailwind css 4", "tailwind framework"],
    "ant design": ["antd", "ant-design", "ant design react"],
    "shadcn/ui": ["shadcn", "shadcn ui", "shadcnui", "shadcn-ui"],
    "styled-components": ["styled components", "styledcomponents"],
    "webpack": ["webpack 4", "webpack 5", "webpack.js"],
    "vite": ["vite.js"],
    "babel": ["babeljs", "babel.js"],
    "storybook": ["storybook.js", "storybookjs"],
    "responsive web design": ["responsive design", "responsive ui", "mobile responsive", "mobile-first design", "responsive layouts",
                              "responsive web development", "rwd"],
    "pwa": ["progressive web apps", "progressive web app", "progressive web application"],
    "spa": ["single page application", "single page applications", "single-page application", "single-page applications"],
    "ssr": ["server side rendering", "server-side rendering"],
    "ssg": ["static site generation", "static site generator", "static site generators"],
    "accessibility": ["web accessibility", "a11y", "accessible design"],
    "cross-browser compatibility": ["cross browser compatibility", "cross browser", "cross-browser testing", "cross browser testing"],
    "dom": ["dom manipulation", "document object model"],
    "ajax": ["ajax calls", "ajax requests"],
    "webassembly": ["wasm", "web assembly"],
    "three.js": ["threejs", "three js"],
    "d3.js": ["d3", "d3js", "d3 js"],
    "chart.js": ["chartjs", "chart js"],
    "framer motion": ["framer-motion"],
    "web development": ["web dev", "web app development", "web application development", "website development",
                        "web applications development", "web design and development"],
    "frontend development": ["front end development", "front-end development", "frontend engineering", "front end engineering",
                             "frontend web development", "front end web development", "web frontend", "client side development",
                             "client-side development"],
    "backend development": ["back end development", "back-end development", "backend engineering", "back end engineering",
                            "server side development", "server-side development", "server side programming", "backend web development"],
    "full-stack development": ["full stack development", "fullstack development", "full stack web development",
                               "full-stack web development", "fullstack web development", "full stack engineering",
                               "full-stack engineering", "fullstack engineering"],
    "software development": ["software engineering", "software dev", "application development", "software programming"],
    "sdlc": ["software development life cycle", "software development lifecycle", "software development life-cycle"],

    # ===== Node / backend frameworks =====
    "node.js": ["node.js development", "node-js", "nodejs development", "node js development", "node.js backend", "nodejs backend"],
    "express": ["express framework", "express.js framework", "expressjs framework"],
    "nest.js": ["nest", "nestjs framework", "nest.js framework"],
    "fastify": ["fastify.js", "fastifyjs"],
    "koa": ["koajs", "koa.js"],
    "hapi": ["hapijs", "hapi.js"],
    "deno": ["deno runtime", "deno.js"],
    "bun": ["bun runtime", "bun.js", "bunjs"],
    "socket.io": ["socketio", "socket io"],
    "websocket": ["websockets", "web sockets", "web socket"],
    "prisma": ["prisma orm"],
    "sequelize": ["sequelize orm", "sequelizejs"],
    "mongoose": ["mongoose odm", "mongoosejs"],
    "drizzle": ["drizzle orm"],
    "yarn": ["yarn package manager"],
    "npm": ["npm package manager"],
    "pnpm": ["pnpm package manager"],

    # ===== Python ecosystem =====
    "flask": ["python flask", "flask framework", "flask python"],
    "django": ["django framework", "django web framework", "django orm", "python django", "django python"],
    "django rest framework": ["django rest", "django-rest", "django rest api", "django rest apis", "django restful api"],
    "fastapi": ["fastapi framework", "fast api framework", "python fastapi", "fastapi python"],
    "starlette": ["starlette framework"],
    "uvicorn": ["uvicorn server"],
    "gunicorn": ["gunicorn server"],
    "celery": ["celery task queue", "celery workers", "celery tasks", "celery beat"],
    "sqlalchemy": ["sqlalchemy orm", "sqlalchemy core"],
    "alembic": ["alembic migrations"],
    "pydantic": ["pydantic models", "pydantic v1", "pydantic validation"],
    "asyncio": ["async io", "python asyncio", "asynchronous programming", "async programming"],
    "multithreading": ["multi-threading", "multi threading", "multithreaded programming", "multi-threaded programming",
                       "java multithreading", "concurrent programming", "concurrency"],
    "unittest": ["unit test framework", "python unittest", "unittest framework"],
    "pytest": ["py.test"],
    "pandas": ["pandas library", "pandas dataframe", "pandas dataframes"],
    "numpy": ["numpy library", "numpy arrays"],
    "scipy": ["scipy library"],
    "matplotlib": ["matplotlib library", "matplotlib.pyplot", "pyplot"],
    "seaborn": ["seaborn library"],
    "beautiful soup": ["beautifulsoup", "beautifulsoup4", "bs4", "beautiful soup 4", "bsoup"],
    "scrapy": ["scrapy framework"],
    "poetry": ["poetry package manager"],
    "conda": ["conda environment", "conda environments", "miniconda", "anaconda"],
    "jupyter": ["jupyter notebook", "jupyter notebooks", "jupyterlab", "jupyter lab", "ipython notebook"],
    "colab": ["google colab", "google colaboratory", "colaboratory"],
    "streamlit": ["streamlit apps", "streamlit app"],
    "langchain": ["lang chain", "lang-chain", "langchain framework"],
    "llamaindex": ["llama index", "llama-index", "llama_index"],
    "openai api": ["openai apis", "chatgpt api", "gpt api", "openai sdk"],
    "openai": ["open ai"],

    # ===== SQL / databases =====
    "sql": ["sql programming", "sql database", "sql databases", "sql language", "sql scripting", "sql development", "sql coding",
            "writing sql queries", "complex sql queries", "advanced sql", "sql joins", "sql analytics", "ansi sql", "sql basics",
            "sql fundamentals"],
    "postgresql": ["postgres sql", "postgre sql", "postgre", "postgresql 12", "postgresql 13", "postgresql 14", "postgresql 15",
                   "postgresql 16", "postgres 12", "postgres 13", "postgres 14", "postgres 15", "postgres 16"],
    "mysql": ["my sql", "my-sql", "mysql server", "mysql 8", "mysql 5.7", "mysql 8.0"],
    "mariadb": ["maria db", "maria-db", "mariadb server"],
    "sql server": ["ms sql server", "mssql server", "microsoft sql", "sql server 2012", "sql server 2014", "sql server 2016",
                   "sql server 2017", "sql server 2019", "sql server 2022", "ms-sql server"],
    "ssms": ["sql server management studio"],
    "ssis": ["sql server integration services"],
    "ssrs": ["sql server reporting services"],
    "ssas": ["sql server analysis services"],
    "oracle": ["oracle sql", "oracle 11g", "oracle 12c", "oracle 19c", "oracle 21c"],
    "plsql": ["oracle pl/sql", "oracle plsql", "pl/sql programming"],
    "tsql": ["transact-sql", "transact sql"],
    "plpgsql": ["pl/pgsql", "pl pgsql"],
    "sqlite": ["sqlite 3"],
    "mongodb": ["mongodb atlas", "mongo atlas", "mongo db atlas"],
    "nosql": ["nosql databases", "nosql database", "no sql", "no-sql", "non relational database", "non-relational database",
              "non relational databases"],
    "redis": ["redis cluster", "redis cloud", "redis sentinel"],
    "memcached": ["memcache", "memcached cache"],
    "elasticsearch": ["elasticsearch 7", "elasticsearch 8"],
    "opensearch": ["amazon opensearch", "aws opensearch", "amazon opensearch service"],
    "kibana": ["kibana dashboards"],
    "logstash": ["logstash pipelines"],
    "cassandra": ["cassandra database", "apache cassandra"],
    "couchdb": ["apache couchdb", "couch db"],
    "couchbase": ["couchbase server"],
    "neo4j": ["neo4j database", "neo 4j"],
    "graph database": ["graph databases", "graph dbs", "graph db"],
    "influxdb": ["influx db", "influxdb database"],
    "timescaledb": ["timescale db", "timescale"],
    "time-series database": ["time series database", "time series databases", "time series db", "tsdb"],
    "snowflake": ["snowflake database", "snowflake data warehouse", "snowflake cloud", "snowflake dw"],
    "bigquery": ["big query", "google bigquery", "gcp bigquery", "google big query", "bigquery sql", "gcp big query"],
    "dbt": ["data build tool", "dbt core", "dbt cloud"],
    "database administration": ["dba", "database admin", "db administration"],
    "database migration": ["db migration", "db migrations", "schema migrations", "database migrations", "schema migration"],
    "database replication": ["db replication"],
    "stored procedures": ["stored procedure", "sql stored procedures", "store procedures", "stored procs"],
    "query optimization": ["query tuning", "sql tuning", "sql optimization", "sql performance tuning", "database tuning",
                           "database optimization", "database performance tuning", "query performance tuning",
                           "sql query optimization", "query optimisation"],
    "acid": ["acid properties", "acid transactions", "acid compliance"],

    # ===== Data engineering / analytics =====
    "spark": ["sparksql", "apache spark framework", "spark framework", "spark core", "spark 3", "apache spark 3", "spark batch"],
    "hive": ["apache hive", "hive sql", "hiveql", "hive ql"],
    "hadoop": ["apache hadoop", "hadoop ecosystem", "hadoop framework", "hadoop mapreduce"],
    "flink": ["apache flink", "flink streaming", "apache flink streaming"],
    "nifi": ["apache nifi"],
    "sqoop": ["apache sqoop"],
    "hbase": ["apache hbase"],
    "superset": ["apache superset"],
    "zookeeper": ["apache zookeeper"],
    "apache iceberg": ["iceberg", "iceberg tables"],
    "apache hudi": ["hudi"],
    "parquet": ["apache parquet", "parquet files", "parquet format"],
    "avro": ["apache avro", "avro format"],
    "delta lake": ["delta lake tables", "delta tables", "databricks delta lake"],
    "databricks": ["azure databricks", "aws databricks", "databricks platform", "databricks notebooks"],
    "informatica": ["informatica powercenter", "informatica cloud", "informatica idmc", "informatica intelligent cloud services"],
    "alteryx": ["alteryx designer"],
    "talend": ["talend open studio", "talend data integration"],
    "big data": ["bigdata", "big-data", "big data technologies", "big data analytics"],
    "data warehousing": ["data warehouse", "data warehouses", "dwh", "edw", "enterprise data warehouse", "data warehouse design"],
    "data lake": ["data lakes", "datalake"],
    "data lakehouse": ["lakehouse", "lakehouse architecture"],
    "data modeling": ["data modelling", "dimensional modeling", "dimensional modelling", "er modeling", "entity relationship modeling"],
    "data pipelines": ["data pipeline", "data pipeline development", "data pipeline design", "data engineering pipelines",
                       "building data pipelines"],
    "etl": ["etl pipelines", "etl pipeline", "etl development", "etl processes", "etl process", "etl tools", "elt",
            "elt pipelines", "etl/elt", "etl and elt"],
    "data cleaning": ["data cleansing", "data wrangling", "data preprocessing", "data pre-processing", "data preparation",
                      "data munging", "data scrubbing"],
    "exploratory data analysis": ["eda"],
    "master data management": ["mdm"],
    "business intelligence": ["bi", "bi tools", "business intelligence tools", "bi reporting", "bi development", "business analytics"],
    "data visualization": ["data visualisation", "data viz", "dataviz", "data visualizations", "data visualization tools",
                           "data visualisation tools"],
    "data analytics": ["data analytic", "data analytics tools"],
    "tableau": ["tableau server", "tableau online", "tableau public", "tableau prep", "tableau dashboards", "tableau reporting"],
    "qlik": ["qlik sense", "qlikview", "qlik view", "qlik cloud"],
    "cognos": ["ibm cognos", "cognos analytics", "cognos bi"],
    "sas": ["sas programming", "sas base", "sas enterprise guide", "sas analytics"],
    "spss": ["ibm spss"],
    "power bi": ["power bi desktop", "power bi service", "microsoft power bi", "ms power bi", "power-bi", "powerbi dashboards"],
    "looker studio": ["google data studio", "data studio", "datastudio", "google looker studio"],
    "airflow": ["airflow dags", "apache airflow dags", "airflow pipelines"],

    # ===== Office / productivity =====
    "microsoft excel": ["ms excel", "excel", "ms-excel", "microsoft excel 365", "excel 365", "excel formulas", "excel pivot tables",
                        "pivot tables"],
    "google sheets": ["gsheets", "g sheets", "google spreadsheets"],
    "google workspace": ["g suite", "gsuite", "google apps", "google workspace admin"],
    "google apps script": ["apps script"],
    "google analytics": ["ga4", "google analytics 4", "universal analytics", "google analytics ga4"],
    "google tag manager": ["gtm", "google tagmanager"],
    "microsoft office": ["ms office", "msoffice", "ms office suite", "office suite", "office 365", "o365", "microsoft 365", "m365",
                         "microsoft office suite", "microsoft office 365"],
    "microsoft powerpoint": ["ms powerpoint", "powerpoint", "power point", "ppt", "ms-powerpoint"],
    "microsoft word": ["ms word", "ms-word"],
    "microsoft access": ["ms access"],
    "microsoft project": ["ms project", "msproject", "ms-project"],
    "microsoft teams": ["ms teams"],
    "sharepoint": ["sharepoint online", "ms sharepoint", "microsoft sharepoint", "sharepoint 365"],
    "power apps": ["powerapps", "microsoft power apps"],
    "power automate": ["microsoft power automate", "microsoft flow", "power automate flows"],
    "power platform": ["microsoft power platform"],

    # ===== AWS =====
    "aws": ["aws services", "amazon cloud", "aws cloud services", "amazon web service", "aws platform", "aws cloud platform"],
    "aws ec2": ["ec2 instances", "amazon elastic compute cloud", "aws ec2 instances", "elastic compute cloud", "amazon ec2 instances"],
    "aws s3": ["amazon simple storage service", "s3 buckets", "aws s3 bucket", "amazon s3 bucket", "simple storage service"],
    "aws rds": ["amazon relational database service", "relational database service"],
    "aws lambda": ["lambda functions", "aws lambda functions", "amazon lambda", "aws lambdas"],
    "aws eks": ["elastic kubernetes service", "aws elastic kubernetes service", "amazon elastic kubernetes service"],
    "aws ecs": ["elastic container service", "aws elastic container service", "amazon elastic container service"],
    "aws cloudwatch": ["amazon cloudwatch", "cloudwatch logs", "aws cloudwatch logs"],
    "aws athena": ["athena", "amazon athena"],
    "aws glue": ["amazon glue", "aws glue jobs", "aws glue etl"],
    "aws sqs": ["sqs", "amazon sqs", "amazon simple queue service", "simple queue service"],
    "aws sns": ["sns", "amazon sns", "amazon simple notification service", "simple notification service"],
    "aws kinesis": ["kinesis", "amazon kinesis", "kinesis streams", "kinesis data streams"],
    "aws emr": ["emr", "amazon emr", "elastic mapreduce", "amazon elastic mapreduce"],
    "aws cloudformation": ["cloudformation", "amazon cloudformation", "cfn", "cloudformation templates"],
    "aws cdk": ["aws cloud development kit", "cloud development kit"],
    "aws api gateway": ["amazon api gateway"],
    "aws cloudfront": ["cloudfront", "amazon cloudfront"],
    "aws route 53": ["route53", "route 53", "amazon route 53", "aws route53"],
    "aws vpc": ["amazon vpc", "aws virtual private cloud", "amazon virtual private cloud"],
    "aws elb": ["elastic load balancer", "aws elastic load balancing", "elastic load balancing"],
    "aws alb": ["application load balancer", "aws application load balancer"],
    "aws ecr": ["amazon ecr", "elastic container registry", "amazon elastic container registry"],
    "aws fargate": ["fargate", "amazon fargate"],
    "aws step functions": ["aws stepfunctions", "amazon step functions"],
    "aws eventbridge": ["eventbridge", "amazon eventbridge", "aws event bridge"],
    "aws secrets manager": ["amazon secrets manager"],
    "aws systems manager": ["aws ssm", "amazon systems manager"],
    "aws cognito": ["cognito", "amazon cognito"],
    "aws sagemaker": ["sagemaker", "amazon sagemaker", "aws sage maker"],
    "aws bedrock": ["bedrock", "amazon bedrock"],
    "aws textract": ["textract", "amazon textract"],
    "aws quicksight": ["quicksight", "amazon quicksight"],
    "aws aurora": ["aurora", "amazon aurora", "aurora postgresql", "aurora mysql"],
    "aws elasticache": ["elasticache", "amazon elasticache"],
    "aws documentdb": ["amazon documentdb"],
    "aws redshift": ["redshift", "amazon redshift"],
    "aws codepipeline": ["codepipeline", "aws code pipeline"],
    "aws codebuild": ["codebuild", "aws code build"],
    "aws codedeploy": ["codedeploy", "aws code deploy"],
    "aws codecommit": ["codecommit", "aws code commit"],
    "aws elastic beanstalk": ["elastic beanstalk", "aws beanstalk", "beanstalk"],
    "aws kms": ["aws key management service", "key management service"],
    "aws cloudtrail": ["cloudtrail", "amazon cloudtrail"],
    "identity and access management": ["aws iam", "amazon iam", "identity access management", "identity & access management"],

    # ===== Azure =====
    "azure": ["azure services", "azure cloud services", "azure platform", "microsoft azure cloud", "azure cloud platform"],
    "azure devops": ["vsts", "visual studio team services", "azure devops services", "azure devops server", "ms azure devops"],
    "azure pipelines": ["azure devops pipelines", "azure pipeline"],
    "azure kubernetes service": ["aks", "azure aks", "azure kubernetes"],
    "azure app service": ["app service", "azure web apps", "azure web app", "azure webapp", "azure webapps"],
    "azure functions": ["azure function apps", "azure function app", "function apps"],
    "azure data factory": ["adf", "azure adf", "data factory", "azure data factory pipelines"],
    "azure synapse analytics": ["synapse", "synapse analytics", "azure synapse", "azure sql data warehouse", "azure sql dw"],
    "microsoft entra id": ["azure ad", "aad", "azure active directory", "entra id", "azure entra id", "microsoft entra"],
    "azure key vault": ["key vault", "keyvault", "azure keyvault"],
    "azure service bus": ["service bus"],
    "azure event hubs": ["azure event hub", "event hubs", "event hub"],
    "azure cosmos db": ["azure cosmosdb", "azure cosmos"],
    "azure application insights": ["application insights", "app insights", "azure appinsights", "azure app insights"],
    "azure storage": ["azure storage account", "azure storage accounts"],
    "azure blob storage": ["azure blobs"],
    "azure container registry": ["acr", "azure acr"],
    "azure container instances": ["aci", "azure aci"],
    "azure container apps": ["azure container app"],
    "azure api management": ["apim", "azure apim"],
    "azure logic apps": ["logic apps"],
    "azure virtual network": ["vnet", "azure vnet", "azure virtual networks"],
    "azure machine learning": ["azure ml", "azure ml studio", "azure machine learning studio"],
    "azure openai": ["azure openai service", "aoai", "azure open ai"],
    "azure ai services": ["azure cognitive services", "cognitive services"],
    "azure bicep": ["bicep"],
    "arm templates": ["arm template", "azure arm templates", "azure resource manager templates", "azure resource manager"],
    "azure monitor": ["azure monitoring"],

    # ===== GCP / Google =====
    "gcp": ["gcp services", "google cloud services", "gcp cloud"],
    "gke": ["gcp gke", "google gke", "gcp kubernetes engine", "gke cluster"],
    "gcp cloud run": ["cloud run", "google cloud run"],
    "gcp cloud functions": ["cloud functions", "gcp functions", "google cloud function", "cloud function"],
    "gcp cloud sql": ["cloud sql", "google cloud sql", "gcp cloudsql"],
    "gcp spanner": ["cloud spanner", "google spanner", "spanner"],
    "gcp bigtable": ["bigtable", "cloud bigtable", "google bigtable"],
    "firestore": ["cloud firestore", "gcp firestore", "google firestore", "firebase firestore"],
    "gcp dataflow": ["dataflow", "cloud dataflow", "google dataflow"],
    "gcp dataproc": ["dataproc", "cloud dataproc", "google dataproc"],
    "gcp cloud composer": ["cloud composer", "gcp composer", "google cloud composer"],
    "vertex ai": ["gcp vertex ai", "google vertex ai", "vertexai", "vertex ai pipelines"],
    "gcp iam": ["google cloud iam", "gcp identity and access management"],
    "gcp cloud storage": ["gcp storage", "gcp gcs", "google gcs"],
    "gcp cloud build": ["cloud build", "google cloud build"],
    "gcp pub/sub": ["gcp pubsub", "google pubsub", "google pub/sub", "cloud pub/sub", "cloud pubsub", "gcp cloud pubsub"],
    "firebase": ["google firebase", "firebase platform"],
    "firebase authentication": ["firebase auth"],
    "firebase cloud messaging": ["fcm"],

    # ===== Containers / DevOps / CI-CD =====
    "docker": ["docker engine", "docker desktop", "docker images", "dockerfile", "dockerfiles", "docker containerization"],
    "docker compose": ["docker compose v2", "docker-compose v2", "docker compose file"],
    "containerization": ["containers", "container technologies", "container technology"],
    "kubernetes": ["k8", "kubernetes k8s", "k8s kubernetes"],
    "openshift": ["open shift", "red hat openshift", "redhat openshift", "openshift container platform"],
    "helm": ["helm 3", "helm v3", "kubernetes helm"],
    "argo cd": ["argocd", "argo-cd"],
    "flux": ["fluxcd", "flux cd"],
    "istio": ["istio service mesh"],
    "terraform": ["terraform cli", "hashicorp terraform", "terraform modules", "terraform infrastructure"],
    "infrastructure as code": ["infra as code"],
    "ansible": ["ansible roles", "ansible tower", "red hat ansible", "ansible awx", "awx", "ansible modules"],
    "puppet": ["puppet enterprise"],
    "chef": ["chef infra"],
    "github actions": ["gh actions", "github action workflows", "github workflows", "github actions ci/cd", "github actions workflows"],
    "gitlab ci/cd": ["gitlab runner", "gitlab pipelines", "gitlab ci/cd pipelines", "gitlab ci pipelines"],
    "circleci": ["circle ci", "circle-ci"],
    "travis ci": ["travisci", "travis-ci"],
    "teamcity": ["team city", "jetbrains teamcity"],
    "bamboo": ["atlassian bamboo", "bamboo ci"],
    "bitbucket pipelines": ["bitbucket ci"],
    "jenkins": ["jenkinsfile", "jenkins pipelines", "jenkins ci/cd", "jenkins automation", "jenkins ci cd"],
    "octopus deploy": ["octopus deployment"],
    "git": ["git version control system", "git cli", "git bash", "source control", "source code management",
            "source control management", "git commands", "distributed version control"],
    "github": ["github enterprise", "github.com"],
    "gitlab": ["gitlab.com", "gitlab enterprise"],
    "bitbucket": ["bitbucket cloud", "bitbucket server", "atlassian bitbucket"],
    "gitflow": ["git flow", "git-flow"],
    "code review": ["code reviews", "peer code review", "code reviewing"],

    # ===== OS / infra / networking =====
    "linux": ["linux administration", "linux admin", "linux system administration", "linux sysadmin", "linux server",
              "linux servers", "linux/unix", "unix/linux", "gnu linux", "linux operating system", "ubuntu", "ubuntu linux",
              "centos", "rhel", "red hat linux", "red hat enterprise linux", "debian", "fedora", "amazon linux",
              "rocky linux", "almalinux", "linux environment"],
    "windows": ["windows os", "microsoft windows", "windows operating system"],
    "active directory": ["microsoft active directory", "windows active directory", "ms active directory"],
    "powershell": ["powershell core", "windows powershell", "pwsh", "powershell automation"],
    "tcp/ip": ["tcp ip", "tcp-ip", "tcpip", "tcp/ip protocol", "tcp/ip networking"],
    "http": ["http protocol", "https", "http/https", "http/2"],
    "vpn": ["virtual private network", "vpns"],
    "ssl/tls": ["ssl tls", "tls/ssl", "ssl", "tls", "ssl certificates", "tls certificates"],
    "firewall": ["firewalls", "firewall configuration"],
    "cdn": ["content delivery network", "content delivery networks"],
    "load balancing": ["loadbalancer", "load balancers", "load balancer configuration"],
    "virtualization": ["virtual machines", "virtual machine", "vms", "server virtualization"],
    "vmware": ["vmware vsphere", "vsphere", "esxi", "vmware esxi", "vcenter", "vmware vcenter"],
    "hyper-v": ["hyperv", "microsoft hyper-v"],
    "virtualbox": ["oracle virtualbox"],
    "apache": ["apache httpd", "apache web server", "httpd", "apache2"],
    "iis": ["microsoft iis", "internet information services"],
    "tomcat": ["apache tomcat"],
    "varnish": ["varnish cache"],
    "cloudflare": ["cloudflare cdn", "cloudflare workers", "cloudflare dns"],
    "caching": ["cache", "cache management", "caching strategies", "caching mechanisms"],
    "performance optimization": ["performance tuning", "performance optimisation", "application performance tuning",
                                 "performance engineering", "application performance optimization"],
    "disaster recovery": ["disaster recovery planning", "dr planning"],
    "backup and recovery": ["backup & recovery", "backups", "data backup", "backup and restore"],

    # ===== Observability =====
    "datadog": ["data dog", "datadog apm", "datadog monitoring"],
    "new relic": ["newrelic", "new-relic"],
    "splunk": ["splunk enterprise", "splunk cloud", "splunk siem"],
    "pagerduty": ["pager duty", "pager-duty"],
    "sentry": ["sentry.io", "sentry io"],
    "prometheus": ["prometheus metrics", "prometheus alerting"],
    "grafana": ["grafana dashboard"],
    "jaeger": ["jaeger tracing"],
    "open telemetry": ["open-telemetry", "opentelemetry collector"],
    "site reliability engineering": ["site reliability", "site reliability engineer"],
    "observability": ["observability tools"],

    # ===== Messaging / APIs / architecture =====
    "kafka": ["amazon msk", "aws msk", "confluent kafka", "confluent platform", "confluent cloud", "kafka cluster"],
    "message queue": ["message brokers", "message broker", "queueing systems", "queue systems"],
    "task queue": ["task queues", "job queue", "job queues", "background jobs", "background tasks", "background job processing"],
    "rabbitmq": ["rabbit-mq"],
    "activemq": ["active mq", "apache activemq"],
    "zeromq": ["zero mq", "0mq"],
    "nats": ["nats.io", "nats messaging"],
    "mqtt": ["mqtt protocol"],
    "amqp": ["amqp protocol"],
    "pub/sub": ["pub sub", "publish subscribe", "publish/subscribe", "pubsub pattern", "pub-sub"],
    "protobuf": ["protocol buffers", "protocol buffer", "proto3"],
    "openapi": ["swagger", "open api", "swagger/openapi", "openapi specification", "openapi 3", "swagger ui", "swagger docs",
                "swagger documentation", "openapi/swagger"],
    "postman": ["postman api", "postman collections", "postman tool"],
    "rest api": ["rest api development", "restful api development", "rest api design", "restful api design",
                 "restful web services", "restful services", "rest services", "rest web services", "restful webservices",
                 "rest web service", "rest endpoints", "restapi", "rest-api", "restful-api", "restful web api",
                 "rest api's", "restful api's", "restful apis development"],
    "api": ["api's"],
    "api integration": ["api integrations", "third party api integration", "third-party api integration",
                        "third party integrations", "third-party integrations"],
    "api testing": ["rest api testing", "api automation testing"],
    "graphql": ["graphql apis", "apollo graphql"],
    "server-sent events": ["sse", "server sent events"],
    "openid connect": ["oidc", "open id connect", "openid"],
    "saml": ["saml 2.0", "saml2", "saml authentication"],
    "ldap": ["ldap authentication", "openldap"],
    "jwt": ["jwt token", "jwt tokens", "jwts"],
    "oauth 2.0": ["oauth", "oauth authentication"],
    "kong": ["kong api gateway", "kong gateway"],
    "mulesoft": ["mule esb", "anypoint", "anypoint platform", "mulesoft anypoint"],
    "microservices": ["microservice architecture", "microservices architecture", "micro services architecture",
                      "microservices architectures", "microservices design", "microservice architectures"],
    "soa": ["service oriented architecture", "service-oriented architecture"],
    "serverless": ["serverless architecture", "serverless computing", "serverless applications", "serverless framework"],
    "hexagonal architecture": ["ports and adapters"],
    "design patterns": ["software design patterns", "gof design patterns", "gang of four", "gang of four patterns", "design pattern"],
    "solid principles": ["solid", "solid design principles", "solid design"],
    "test-driven development": ["tdd", "test driven development"],
    "behavior-driven development": ["bdd", "behavior driven development", "behaviour driven development", "behaviour-driven development"],
    "system design": ["software architecture", "architecture design"],
    "distributed systems": ["distributed system", "distributed computing", "distributed architecture"],
    "oop": ["oop concepts", "oops concepts", "oop principles", "object oriented design", "object-oriented design", "ood",
            "object oriented concepts", "object-oriented concepts"],
    "dsa": ["data structures and algorithm", "ds & algo", "algorithms and data structures", "algorithms & data structures",
            "data structure and algorithms", "data structures algorithms", "data structure & algorithms", "data structures",
            "algorithms"],

    # ===== AI / ML =====
    "machine learning": ["machine-learning", "ml models", "machine learning models", "machine learning algorithms",
                         "ml algorithms", "applied machine learning"],
    "deep learning": ["deep-learning", "deep learning models"],
    "neural networks": ["neural network", "artificial neural networks", "artificial neural network", "ann"],
    "convolutional neural networks": ["cnn", "cnns", "convolutional neural network"],
    "recurrent neural networks": ["rnn", "rnns", "recurrent neural network"],
    "lstm": ["long short term memory", "long short-term memory"],
    "generative adversarial networks": ["gan", "gans", "generative adversarial network"],
    "transformers": ["transformer models", "transformer architecture", "transformer networks"],
    "bert": ["bert model", "bert models"],
    "gpt": ["gpt models", "gpt-3", "gpt-3.5", "gpt-4", "gpt-4o", "gpt3", "gpt4", "chatgpt", "chat gpt", "openai gpt"],
    "llm": ["llm models", "llm applications", "llm apps", "llm application development", "llm integration", "llm development"],
    "foundation models": ["foundation model"],
    "prompt engineering": ["prompt design", "prompt-engineering", "prompting", "prompt engineering techniques"],
    "retrieval-augmented generation": ["rag", "rag pipeline", "rag pipelines", "rag systems", "rag architecture",
                                       "retrieval augmented generation", "rag applications"],
    "fine-tuning": ["fine tuning", "finetuning", "llm fine-tuning", "llm fine tuning", "model fine-tuning", "model fine tuning"],
    "embeddings": ["text embeddings", "vector embeddings", "embedding models", "word embeddings"],
    "vector database": ["vector dbs", "vector search database"],
    "faiss": ["faiss library", "facebook faiss"],
    "ai agents": ["agentic ai", "agentic workflows", "llm agents", "ai agent", "agentic systems", "autonomous agents"],
    "model context protocol": ["mcp"],
    "hugging face": ["huggingface hub", "hf hub", "hugging face hub"],
    "pytorch": ["py torch", "pytorch framework"],
    "tensorflow": ["tensor flow", "tensorflow 2", "tensorflow2", "tf2", "tensorflow framework"],
    "keras": ["keras api", "tf.keras"],
    "scikit-learn": ["sci-kit learn", "scikitlearn", "sk-learn"],
    "xgboost": ["xgb", "xg boost"],
    "lightgbm": ["light gbm"],
    "catboost": ["cat boost"],
    "opencv": ["open cv", "opencv-python", "cv2"],
    "yolo": ["yolov5", "yolov8", "yolov7", "yolov3"],
    "ner": ["named entity recognition"],
    "spacy": ["spacy nlp"],
    "nltk": ["natural language toolkit"],
    "predictive modeling": ["predictive modelling", "predictive analytics"],
    "statistics": ["statistical analysis", "statistical modeling", "statistical modelling", "applied statistics"],
    "a/b testing": ["ab testing", "a b testing", "split testing", "a/b tests", "a-b testing"],
    "model deployment": ["ml deployment", "model serving", "model deployments"],
    "mlops": ["ml ops", "ml-ops", "machine learning operations"],
    "mlflow": ["ml flow"],
    "weights & biases": ["wandb", "weights and biases", "w&b"],
    "onnx": ["onnx runtime"],
    "generative ai": ["generative artificial intelligence", "gen-ai"],

    # ===== Testing / QA =====
    "unit testing": ["unit test", "unit testing frameworks"],
    "junit": ["junit 4", "junit 5", "junit4", "junit5", "junit testing"],
    "testng": ["testng framework"],
    "mockito": ["mockito framework"],
    "jest": ["jest testing", "jest framework"],
    "react testing library": ["rtl", "testing library", "react-testing-library"],
    "cypress": ["cypress testing", "cypress e2e", "cypress.js"],
    "playwright": ["playwright.js"],
    "puppeteer": ["puppeteer.js", "puppeteerjs"],
    "selenium": ["selenium grid", "selenium ide", "selenium automation", "selenium testing", "selenium python", "selenium java"],
    "webdriverio": ["webdriver io"],
    "appium": ["appium mobile testing"],
    "robot framework": ["robotframework"],
    "cucumber": ["cucumber bdd", "cucumber.js", "gherkin"],
    "jmeter": ["apache jmeter"],
    "performance testing": ["load testing", "stress testing", "performance tests", "load and performance testing"],
    "k6": ["grafana k6"],
    "soapui": ["soap ui"],
    "uat": ["user acceptance testing", "uat testing"],
    "end-to-end testing": ["end to end testing", "e2e testing", "e2e tests", "e2e", "end to end tests", "end-to-end tests"],
    "integration testing": ["integration test", "integration testing frameworks"],
    "test automation": ["automation testing", "automated tests", "test automation frameworks", "test automation framework",
                        "qa automation", "automation framework", "automation frameworks"],
    "manual testing": ["manual qa", "manual test"],
    "functional testing": ["functional tests"],
    "regression testing": ["regression tests"],
    "bug tracking": ["defect tracking", "issue tracking", "bug tracker"],

    # ===== Security =====
    "owasp": ["owasp top 10", "owasp top ten"],
    "penetration testing": ["pen testing", "pentesting", "pen test", "pentest", "ethical hacking"],
    "vulnerability assessment": ["vulnerability management", "vulnerability scanning", "vulnerability analysis"],
    "siem": ["security information and event management"],
    "iso 27001": ["iso27001", "iso/iec 27001", "iso 27001:2013", "iso 27001:2022"],
    "soc 2": ["soc2", "soc 2 compliance"],
    "gdpr": ["gdpr compliance"],
    "hipaa": ["hipaa compliance"],
    "pci dss": ["pci-dss", "pci compliance", "pci dss compliance"],
    "nist": ["nist framework", "nist csf", "nist cybersecurity framework"],
    "devsecops": ["dev sec ops", "dev-sec-ops"],
    "sast": ["static application security testing"],
    "dast": ["dynamic application security testing"],
    "sonarqube": ["sonar qube", "sonarcloud"],
    "burp suite": ["burpsuite", "burp"],
    "privileged access management": ["pam"],
    "okta": ["okta sso"],
    "auth0": ["auth 0"],
    "abac": ["attribute based access control", "attribute-based access control"],
    "rbac": ["role based access", "role-based access"],

    # ===== Java / .NET ecosystems =====
    "spring boot": ["spring boot framework", "spring boot 2", "spring boot 3", "spring boot microservices"],
    "spring": ["spring mvc", "spring web", "spring ioc"],
    "jdbc": ["java jdbc"],
    "weblogic": ["oracle weblogic"],
    "websphere": ["ibm websphere"],
    "servlets": ["java servlets", "servlet", "jsp/servlets"],
    "struts": ["apache struts"],
    "jax-rs": ["jaxrs", "jax rs"],
    "lombok": ["project lombok"],
    ".net": ["dotnet core", "dot net core", ".net core", "net core", ".net 5", ".net 6", ".net 7", ".net 8", ".net 9",
             "dotnet 5", "dotnet 6", "dotnet 7", "dotnet 8", "dotnet 9", ".net 6.0", ".net 8.0", ".net development",
             "dotnet development", ".net framework", "dotnet framework"],
    "asp.net": ["asp net", "aspnet"],
    "asp.net mvc": ["asp net mvc", "aspnet mvc", "asp.net mvc 5"],
    "asp.net web api": ["aspnet web api", "asp net web api", "asp.net webapi"],
    "entity framework": ["ef", "entity framework 6", "ef6"],
    "linq": ["linq to sql", "linq queries"],
    "wpf": ["windows presentation foundation"],
    "winforms": ["windows forms", "win forms"],
    ".net maui": ["maui"],
    "blazor": ["blazor server", "blazor webassembly", "blazor wasm"],
    "signalr": ["asp.net signalr"],
    "nuget": ["nuget packages"],
    "visual studio code": ["vs code", "vscode", "vs-code"],
    "visual studio": ["ms visual studio", "visual studio 2019", "visual studio 2022", "visual studio ide"],
    "intellij idea": ["intellij", "intellij ide", "jetbrains intellij"],
    "pycharm": ["pycharm ide", "jetbrains pycharm"],
    "eclipse": ["eclipse ide"],
    "android studio": ["android studio ide"],
    "xcode": ["xcode ide"],

    # ===== Mobile =====
    "android": ["android app development", "android application development", "android dev", "native android", "android native"],
    "jetpack compose": ["android jetpack compose"],
    "ios": ["ios app development", "ios application development", "native ios", "ios native", "iphone development",
            "iphone app development"],
    "uikit": ["ui kit"],
    "react native": ["reactnative", "react native cli", "react native development", "react-native development"],
    "flutter": ["flutter sdk", "flutter framework", "flutter app development", "flutter dart"],
    "dart": ["dart programming", "dart lang"],
    "xamarin": ["xamarin.forms", "xamarin forms", "xamarin android", "xamarin ios"],
    "ionic": ["ionic framework"],
    "cordova": ["apache cordova", "phonegap"],
    "mobile development": ["mobile app development", "mobile application development", "mobile apps", "mobile app dev"],
    "cross-platform development": ["cross platform mobile development", "cross platform development", "cross-platform mobile development"],
    "apns": ["apple push notification service", "apple push notifications"],

    # ===== Process / soft skills =====
    "agile": ["agile practices", "agile methods", "agile principles", "agile scrum", "agile software development",
              "agile ways of working"],
    "scrum": ["scrum process", "scrum ceremonies", "scrum agile"],
    "safe": ["scaled agile framework", "scaled agile"],
    "kanban": ["kanban board", "kanban boards"],
    "waterfall": ["waterfall methodology", "waterfall model"],
    "confluence": ["atlassian confluence"],
    "stakeholder management": ["stakeholder communication", "stakeholder engagement", "stakeholder relations"],
    "requirements gathering": ["requirement gathering", "requirements analysis", "requirement analysis",
                               "requirements elicitation", "requirement elicitation", "business requirements gathering"],
    "technical documentation": ["documentation", "technical docs", "tech documentation", "technical writing"],
    "communication": ["communication skills", "verbal communication", "written communication", "verbal and written communication",
                      "effective communication", "excellent communication skills"],
    "teamwork": ["team work", "team collaboration", "collaboration", "team player", "working in teams"],
    "problem solving": ["problem-solving", "problem solving skills", "problem solving abilities", "problem-solving skills"],
    "analytical skills": ["analytical thinking", "analytical abilities", "analytical"],
    "critical thinking": ["critical-thinking"],
    "leadership": ["leadership skills", "team leadership", "leading teams"],
    "team management": ["people management", "managing teams", "team handling"],
    "time management": ["time-management"],
    "presentation skills": ["public speaking", "presentations"],
    "negotiation": ["negotiation skills"],
    "mentoring": ["mentorship", "coaching", "mentoring and coaching"],
    "attention to detail": ["detail oriented", "detail-oriented"],

    # ===== Design =====
    "ui/ux": ["ui design", "ux design", "user experience design", "user interface design", "ui and ux", "ui & ux", "ux/ui",
              "ux/ui design", "ui-ux", "user experience", "user interface", "ui/ux designing"],
    "figma": ["figma design", "figma ui", "figma prototyping"],
    "adobe photoshop": ["photoshop"],
    "adobe illustrator": ["illustrator"],
    "sketch": ["sketch app"],
    "invision": ["invision studio"],
    "wireframing": ["wireframes", "wire framing", "wireframes and prototypes"],
    "design systems": ["design system"],

    # ===== ERP / CRM / CMS =====
    "sap": ["sap erp", "sap ecc"],
    "sap s/4hana": ["sap s4hana", "s4hana", "s/4hana", "sap s/4 hana", "sap s4 hana"],
    "abap": ["sap abap", "abap programming"],
    "salesforce": ["salesforce crm", "salesforce.com", "sfdc", "salesforce platform", "salesforce cloud"],
    "salesforce apex": ["apex", "apex programming"],
    "lightning web components": ["lwc"],
    "servicenow": ["service now", "service-now", "servicenow platform"],
    "dynamics 365": ["microsoft dynamics 365", "ms dynamics", "dynamics crm", "microsoft dynamics", "d365", "dynamics 365 crm"],
    "hubspot": ["hubspot crm"],
    "shopify": ["shopify development", "shopify platform"],
    "wordpress": ["wordpress development", "wordpress cms", "wp"],
    "woocommerce": ["woo commerce"],
    "magento": ["magento 2", "magento2"],
    "drupal": ["drupal cms"],
    "cms": ["content management system", "content management systems"],
    "crm": ["customer relationship management", "crm systems", "crm software"],
    "erp": ["enterprise resource planning", "erp systems", "erp software"],

    # ===== Blockchain / games / embedded / engineering =====
    "blockchain": ["blockchain technology", "blockchain development", "distributed ledger", "distributed ledger technology", "dlt"],
    "ethereum": ["ethereum blockchain"],
    "solidity": ["solidity programming", "solidity language", "solidity smart contracts"],
    "web3.js": ["web3js"],
    "ethers.js": ["ethersjs"],
    "unity": ["unity 3d", "unity3d", "unity engine", "unity game engine", "unity game development"],
    "unreal engine": ["unreal engine 4", "unreal engine 5", "ue4", "ue5", "unreal"],
    "godot": ["godot engine"],
    "game development": ["game dev", "game programming"],
    "embedded systems": ["embedded c", "embedded c/c++", "embedded programming", "embedded software",
                         "embedded systems development", "embedded software development"],
    "rtos": ["real time operating system", "real-time operating system", "real time operating systems", "real-time operating systems"],
    "arduino": ["arduino platform"],
    "raspberry pi": ["rpi", "raspberrypi", "raspberry pi 4"],
    "iot": ["internet of things", "iot development", "iot platforms"],
    "plc": ["plc programming", "programmable logic controllers", "programmable logic controller"],
    "scada": ["scada systems"],
    "fpga": ["fpga development"],
    "pcb design": ["pcb layout", "printed circuit board design"],
    "autocad": ["auto cad", "autodesk autocad"],
    "solidworks": ["solid works", "solidworks cad"],
    "labview": ["lab view"],
    "cad": ["computer aided design", "computer-aided design"],
    "cnc": ["cnc programming", "cnc machining", "cnc machines"],
    "gd&t": ["gdt", "geometric dimensioning and tolerancing", "geometric dimensioning & tolerancing"],
    "3d printing": ["additive manufacturing"],
    "hvac": ["heating ventilation and air conditioning"],
    "digsilent": ["digsilent powerfactory", "power factory", "dig silent"],
    "pvsyst": ["pv syst"],
    "primavera p6": ["primavera", "oracle primavera", "primavera p6 scheduling"],
    "six sigma": ["6 sigma", "lean six sigma", "six-sigma", "lss"],
    "lean manufacturing": ["lean mfg", "lean production"],
    "fmea": ["failure mode and effects analysis", "failure mode effects analysis", "failure modes and effects analysis"],
    "root cause analysis": ["rca", "5 whys", "5-why analysis", "5 why analysis"],
    "statistical process control": ["spc"],
    "total productive maintenance": ["tpm"],
    "iso 9001": ["iso9001", "iso 9001:2015"],
    "iso 14001": ["iso14001", "iso 14001:2015"],
    "quality management system": ["quality management systems", "qms"],
    "quality control": ["qc"],
    "supply chain management": ["supply chain"],
    "inventory management": ["inventory control"],
    "5s": ["5s methodology", "5s system"],
}


def _build_skill_aliases(
    curated: dict[str, str],
    groups: dict[str, list[str]],
) -> dict[str, str]:
    merged = dict(curated)
    for canonical, variants in groups.items():
        for variant in variants:
            key = variant.strip().lower()
            if key and key != canonical:
                merged.setdefault(key, canonical)
    return merged


SKILL_ALIASES = _build_skill_aliases(CURATED_ALIASES, EXTRA_GROUPS)